"""
Django settings for skylinkwebsiteadmin project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!9v0$3tyuu3g4g%et%qk-hkp&x%h8673-ukj0!lq#o+&&s+g6&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contactus',
    'rest_framework',
    'corsheaders',
    'fisability',
    "subscription",
    'import_export',
    'call3cx',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skylinkwebsiteadmin.urls'
#CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'skylinkwebsiteadmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'skylinkdb',        # your database name
        'USER': 'root',             # your MySQL username
        'PASSWORD': '',  # your MySQL password
        'HOST': 'localhost',        # or your DB host
        'PORT': '3306',             # default MySQL port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {
    "site_title": "Skylink Admin",
    "site_header": "Skylink Admin Panel",
    "welcome_sign": "Welcome to Skylink Dashboard",
    "show_sidebar": True,
    "navigation_expanded": False,  # default collapsed
    "hide_apps": [],  # you can hide apps if needed
    "icons": {
        "auth": "fas fa-users-cog",
        "contactus": "fas fa-envelope",
    },
    "order_with_respect_to_apps": ["contactus", "auth", "sessions"],  # order apps
    "custom_links": {
        "contactus": [{
            "name": "All Contacts",
            "url": "/admin/contactus/contactus/",
            "icon": "fas fa-envelope-open-text",
            "permissions": ["contactus.view_contactus"]
        }],
    },
}



# Use env vars for secrets and 3cx host
import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

# Example; place in .env (see below)
THREECX_MAKECALL_URL = os.getenv("THREECX_MAKECALL_URL", "")
THREECX_ORIGINATOR = os.getenv("THREECX_ORIGINATOR", "100")
CALL_API_SECRET = os.getenv("CALL_API_SECRET", "sdafsf")


GOOGLE_API_KEY = "AIzaSyBfl9FeQrq_J6IdVBRMzBJWm6enyJvjGQ4"