# Generated by Django 4.2.19 on 2025-10-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fisability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circlename', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('regionname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('divisionname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('officename', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('officetype', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('delivery', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('statename', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
