# Generated by Django 4.2.19 on 2025-11-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('area_name', models.CharField(default='Unnamed Area', max_length=100)),
                ('center_lat', models.FloatField(default=0.0)),
                ('center_lng', models.FloatField(default=0.0)),
                ('radius_km', models.FloatField(default=1.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Fisability',
        ),
    ]
