# Generated by Django 4.2.19 on 2025-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
