# Generated by Django 4.2.19 on 2025-11-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_alter_contactus_options_alter_contactus_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoLeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_logs', to='contactus.contactus')),
            ],
            options={
                'verbose_name': 'Zoho Lead Log',
                'verbose_name_plural': 'Zoho Lead Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
